version: '3.4'
services:
    rsu:
        hostname: rsu
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
            - VANETZA_LATITUDE=40.6429
            - VANETZA_LONGITUDE=-8.65608
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    rsu2:
        hostname: rsu2
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
            - VANETZA_LATITUDE=40.64255
            - VANETZA_LONGITUDE=-8.65568
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.11
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    vru1:
        hostname: vru
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    vru2:
        hostname: vru
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=4
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.21
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536
    
        ##################################################################################
    ## Cluster PEER 0 ################################################################
    ##################################################################################

    ipfs0:
        container_name: ipfs0
        image: ipfs/kubo:release
        ports:
         - "4001:4001" # ipfs swarm - expose if needed/wanted
         - "5001:5001" # ipfs api - expose if needed/wante
         - "8080:8080" # ipfs gateway - expose if needed/wanted
        volumes:
         - ./compose/ipfs0:/data/ipfs

    cluster0:
        container_name: cluster0
        image: ipfs/ipfs-cluster:latest
        depends_on:
         - ipfs0
        environment:
            CLUSTER_PEERNAME: cluster0
            CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
            CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
            CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
            CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
            CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
        ports:
            # Open API port (allows ipfs-cluster-ctl usage on host)
            - "127.0.0.1:9094:9094"
            # The cluster swarm port would need  to be exposed if this container
            # was to connect to cluster peers on other hosts.
            # But this is just a testing cluster.
            # - "9095:9095" # Cluster IPFS Proxy endpoint
            # - "9096:9096" # Cluster swarm endpoint
        volumes:
         - ./compose/cluster0:/data/ipfs-cluster

    ##################################################################################
    ## Cluster PEER 1 ################################################################
    ##################################################################################

    # See Cluster PEER 0 for comments (all removed here and below)
    ipfs1:
        container_name: ipfs1
        image: ipfs/kubo:release
        volumes:
         - ./compose/ipfs1:/data/ipfs

    cluster1:
        container_name: cluster1
        image: ipfs/ipfs-cluster:latest
        depends_on:
         - ipfs1
        environment:
            CLUSTER_PEERNAME: cluster1
            CLUSTER_SECRET: ${CLUSTER_SECRET}
            CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
            CLUSTER_CRDT_TRUSTEDPEERS: '*'
            CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
        volumes:
         - ./compose/cluster1:/data/ipfs-cluster

    ##################################################################################
    ## Cluster PEER 2 ################################################################
    ##################################################################################

    # See Cluster PEER 0 for comments (all removed here and below)
    ipfs2:
        container_name: ipfs2
        image: ipfs/kubo:release
        volumes:
         - ./compose/ipfs2:/data/ipfs

    cluster2:
        container_name: cluster2
        image: ipfs/ipfs-cluster:latest
        depends_on:
         - ipfs2
        environment:
            CLUSTER_PEERNAME: cluster2
            CLUSTER_SECRET: ${CLUSTER_SECRET}
            CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
            CLUSTER_CRDT_TRUSTEDPEERS: '*'
            CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
        volumes:
         - ./compose/cluster2:/data/ipfs-cluster

    # For adding more peers, copy PEER 1 and rename things to ipfs2, cluster2.
    # Keep bootstrapping to cluster0.
    
  
networks:
  vanetzalan0:
    external: true